version: '3.8'

services:
  postgres-15:
    image: postgres:15
    ports:
      - "5432:5432"
    #    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-korisnik}
      POSTGRES_PASSWORD: ${DB_PASS:-lozinka}
      POSTGRES_DB: ${DB_SCHEMA:-shema}
